name: "Deploy Extraction Pipelines"
description: "Deploy a set of Extraction Pipelines from yaml manifests"
inputs:
  token-url:
    description: "Token url to use for fetching OAuth2 tokens"
    required: false
  cdf-project-name:
    description: "CDF project name (only required when using OAuth2 credentials)"
    required: false
  scopes:
    description: "List of OAuth2 scopes (space separated)"
    required: false
  audience:
    description: "OAuth2 audience"
    required: false
  client-id:
    description: "OAuth2 client ID"
    required: false
  client-secret:
    description: "OAuth2 client secret"
    required: false
  cluster:
    description: "CDF Cluster"
    required: false
    default: "api"
  config_file:
    description: >-
      The path to a yaml file containing Extraction Pipeline configuration.
      This is relative to $GITHUB_WORKSPACE,
      which will be the root of the repository when using actions/checkout with default settings.
    required: true
runs:
  using: "docker"
  image: docker://cognite/extpipes-cli:v3.0.0-beta1
  env:
    CDF_TOKEN_URL: ${{ inputs.token-url }}
    CDF_PROJECT: ${{ inputs.cdf-project-name }}
    CDF_CLIENT_ID: ${{ inputs.client-id }}
    CDF_CLIENT_SECRET: ${{ inputs.client-secret }}
    CDF_SCOPES: ${{ inputs.scopes }}
    CDF_AUDIENCE: ${{ inputs.audience }}
    CDF_CLUSTER: "${{ inputs.cluster }}"
  args: ["deploy", "${{ inputs.config_file }}"]
